"""
The MLB games tracked by live_recorder.py.

Current slate: 15 games, HKT date(s) 2026-09-09.
Polymarket slugs carry the US date.

Generated by plan_slate.py -- do not hand-edit; regenerate instead.
"""

matches = [
    {
        "time_hkt": "06:35",
        "match": "Cleveland Guardians vs. Baltimore Orioles",
        "slug": "mlb-cle-bal-2026-09-08",
        "gamePk": 824792,
    },
    {
        "time_hkt": "06:40",
        "match": "Minnesota Twins vs. Detroit Tigers",
        "slug": "mlb-min-det-2026-09-08",
        "gamePk": 824228,
    },
    {
        "time_hkt": "06:40",
        "match": "Houston Astros vs. Philadelphia Phillies",
        "slug": "mlb-hou-phi-2026-09-08",
        "gamePk": 823414,
    },
    {
        "time_hkt": "06:40",
        "match": "New York Mets vs. Miami Marlins",
        "slug": "mlb-nym-mia-2026-09-08",
        "gamePk": 823821,
    },
    {
        "time_hkt": "06:45",
        "match": "Los Angeles Angels vs. Boston Red Sox",
        "slug": "mlb-laa-bos-2026-09-08",
        "gamePk": 824714,
    },
    {
        "time_hkt": "07:05",
        "match": "Colorado Rockies vs. New York Yankees",
        "slug": "mlb-col-nyy-2026-09-08",
        "gamePk": 823500,
    },
    {
        "time_hkt": "07:15",
        "match": "Tampa Bay Rays vs. Atlanta Braves",
        "slug": "mlb-tb-atl-2026-09-08",
        "gamePk": 824875,
    },
    {
        "time_hkt": "07:40",
        "match": "Arizona Diamondbacks vs. Kansas City Royals",
        "slug": "mlb-ari-kc-2026-09-08",
        "gamePk": 824063,
    },
    {
        "time_hkt": "07:40",
        "match": "Pittsburgh Pirates vs. Chicago White Sox",
        "slug": "mlb-pit-cws-2026-09-08",
        "gamePk": 824551,
    },
    {
        "time_hkt": "07:40",
        "match": "Chicago Cubs vs. Milwaukee Brewers",
        "slug": "mlb-chc-mil-2026-09-08",
        "gamePk": 823738,
    },
    {
        "time_hkt": "09:40",
        "match": "Washington Nationals vs. San Diego Padres",
        "slug": "mlb-wsh-sd-2026-09-08",
        "gamePk": 823250,
    },
    {
        "time_hkt": "09:40",
        "match": "Texas Rangers vs. Seattle Mariners",
        "slug": "mlb-tex-sea-2026-09-08",
        "gamePk": 823092,
    },
    {
        "time_hkt": "09:40",
        "match": "Toronto Blue Jays vs. Athletics",
        "slug": "mlb-tor-oak-2026-09-08",
        "gamePk": 824957,
    },
    {
        "time_hkt": "09:45",
        "match": "St. Louis Cardinals vs. San Francisco Giants",
        "slug": "mlb-stl-sf-2026-09-08",
        "gamePk": 823174,
    },
    {
        "time_hkt": "10:10",
        "match": "Cincinnati Reds vs. Los Angeles Dodgers",
        "slug": "mlb-cin-lad-2026-09-08",
        "gamePk": 823901,
    },
]
