"""
The MLB games tracked by live_recorder.py.

Current slate: 15 games, HKT date(s) 2026-09-21.
Polymarket slugs carry the US date.

Generated by plan_slate.py -- do not hand-edit; regenerate instead.
"""

matches = [
    {
        "time_hkt": "01:10",
        "match": "Philadelphia Phillies vs. New York Mets",
        "slug": "mlb-phi-nym-2026-09-20",
        "gamePk": 823570,
    },
    {
        "time_hkt": "01:35",
        "match": "Kansas City Royals vs. Pittsburgh Pirates",
        "slug": "mlb-kc-pit-2026-09-20",
        "gamePk": 823329,
    },
    {
        "time_hkt": "01:40",
        "match": "Chicago Cubs vs. Cincinnati Reds",
        "slug": "mlb-chc-cin-2026-09-20",
        "gamePk": 824462,
    },
    {
        "time_hkt": "01:40",
        "match": "Athletics vs. Cleveland Guardians",
        "slug": "mlb-oak-cle-2026-09-20",
        "gamePk": 824381,
    },
    {
        "time_hkt": "01:40",
        "match": "Boston Red Sox vs. Tampa Bay Rays",
        "slug": "mlb-bos-tb-2026-09-20",
        "gamePk": 822922,
    },
    {
        "time_hkt": "02:10",
        "match": "Atlanta Braves vs. Houston Astros",
        "slug": "mlb-atl-hou-2026-09-20",
        "gamePk": 824139,
    },
    {
        "time_hkt": "02:10",
        "match": "Detroit Tigers vs. Chicago White Sox",
        "slug": "mlb-det-cws-2026-09-20",
        "gamePk": 824546,
    },
    {
        "time_hkt": "02:15",
        "match": "Washington Nationals vs. St. Louis Cardinals",
        "slug": "mlb-wsh-stl-2026-09-20",
        "gamePk": 823001,
    },
    {
        "time_hkt": "02:35",
        "match": "Toronto Blue Jays vs. Texas Rangers",
        "slug": "mlb-tor-tex-2026-09-20",
        "gamePk": 822844,
    },
    {
        "time_hkt": "03:10",
        "match": "Seattle Mariners vs. Colorado Rockies",
        "slug": "mlb-sea-col-2026-09-20",
        "gamePk": 824300,
    },
    {
        "time_hkt": "04:07",
        "match": "Minnesota Twins vs. Los Angeles Angels",
        "slug": "mlb-min-laa-2026-09-20",
        "gamePk": 823975,
    },
    {
        "time_hkt": "04:10",
        "match": "San Francisco Giants vs. Los Angeles Dodgers",
        "slug": "mlb-sf-lad-2026-09-20",
        "gamePk": 823896,
    },
    {
        "time_hkt": "04:10",
        "match": "Miami Marlins vs. San Diego Padres",
        "slug": "mlb-mia-sd-2026-09-20",
        "gamePk": 823247,
    },
    {
        "time_hkt": "04:10",
        "match": "New York Yankees vs. Arizona Diamondbacks",
        "slug": "mlb-nyy-ari-2026-09-20",
        "gamePk": 825028,
    },
    {
        "time_hkt": "07:20",
        "match": "Milwaukee Brewers vs. Baltimore Orioles",
        "slug": "mlb-mil-bal-2026-09-20",
        "gamePk": 824789,
    },
]
