"""
The MLB games tracked by live_recorder.py.

Current slate: 14 games, HKT date(s) 2026-09-28.
Polymarket slugs carry the US date.

Generated by plan_slate.py -- do not hand-edit; regenerate instead.
"""

matches = [
    {
        "time_hkt": "01:05",
        "match": "New York Mets vs. Washington Nationals",
        "slug": "mlb-nym-wsh-2026-09-27",
        "gamePk": 822679,
    },
    {
        "time_hkt": "01:05",
        "match": "Baltimore Orioles vs. New York Yankees",
        "slug": "mlb-bal-nyy-2026-09-27",
        "gamePk": 823490,
    },
    {
        "time_hkt": "02:30",
        "match": "Tampa Bay Rays vs. Philadelphia Phillies",
        "slug": "mlb-tb-phi-2026-09-27",
        "gamePk": 823408,
    },
    {
        "time_hkt": "03:05",
        "match": "Houston Astros vs. Athletics",
        "slug": "mlb-hou-oak-2026-09-27",
        "gamePk": 824948,
    },
    {
        "time_hkt": "03:05",
        "match": "Los Angeles Dodgers vs. San Francisco Giants",
        "slug": "mlb-lad-sf-2026-09-27",
        "gamePk": 823164,
    },
    {
        "time_hkt": "03:07",
        "match": "Cincinnati Reds vs. Toronto Blue Jays",
        "slug": "mlb-cin-tor-2026-09-27",
        "gamePk": 822761,
    },
    {
        "time_hkt": "03:10",
        "match": "Cleveland Guardians vs. Kansas City Royals",
        "slug": "mlb-cle-kc-2026-09-27",
        "gamePk": 824055,
    },
    {
        "time_hkt": "03:10",
        "match": "Pittsburgh Pirates vs. Detroit Tigers",
        "slug": "mlb-pit-det-2026-09-27",
        "gamePk": 824217,
    },
    {
        "time_hkt": "03:10",
        "match": "Arizona Diamondbacks vs. San Diego Padres",
        "slug": "mlb-ari-sd-2026-09-27",
        "gamePk": 823246,
    },
    {
        "time_hkt": "03:10",
        "match": "Los Angeles Angels vs. Seattle Mariners",
        "slug": "mlb-laa-sea-2026-09-27",
        "gamePk": 823084,
    },
    {
        "time_hkt": "03:10",
        "match": "Texas Rangers vs. Minnesota Twins",
        "slug": "mlb-tex-min-2026-09-27",
        "gamePk": 823650,
    },
    {
        "time_hkt": "03:10",
        "match": "Colorado Rockies vs. Chicago White Sox",
        "slug": "mlb-col-cws-2026-09-27",
        "gamePk": 824542,
    },
    {
        "time_hkt": "03:10",
        "match": "Atlanta Braves vs. Miami Marlins",
        "slug": "mlb-atl-mia-2026-09-27",
        "gamePk": 823814,
    },
    {
        "time_hkt": "03:10",
        "match": "St. Louis Cardinals vs. Milwaukee Brewers",
        "slug": "mlb-stl-mil-2026-09-27",
        "gamePk": 823731,
    },
]
