"""
The MLB games tracked by live_recorder.py.

Current slate: 15 games, HKT date(s) 2026-09-02.
Polymarket slugs carry the US date.

Generated by plan_slate.py -- do not hand-edit; regenerate instead.
"""

matches = [
    {
        "time_hkt": "06:40",
        "match": "San Diego Padres vs. Cincinnati Reds",
        "slug": "mlb-sd-cin-2026-09-01",
        "gamePk": 824472,
    },
    {
        "time_hkt": "06:40",
        "match": "San Francisco Giants vs. Pittsburgh Pirates",
        "slug": "mlb-sf-pit-2026-09-01",
        "gamePk": 823340,
    },
    {
        "time_hkt": "06:40",
        "match": "New York Mets vs. Tampa Bay Rays",
        "slug": "mlb-nym-tb-2026-09-01",
        "gamePk": 822929,
    },
    {
        "time_hkt": "06:40",
        "match": "Toronto Blue Jays vs. Cleveland Guardians",
        "slug": "mlb-tor-cle-2026-09-01",
        "gamePk": 824391,
    },
    {
        "time_hkt": "06:45",
        "match": "Seattle Mariners vs. Boston Red Sox",
        "slug": "mlb-sea-bos-2026-09-01",
        "gamePk": 824716,
    },
    {
        "time_hkt": "06:45",
        "match": "Atlanta Braves vs. Washington Nationals",
        "slug": "mlb-atl-wsh-2026-09-01",
        "gamePk": 822687,
    },
    {
        "time_hkt": "07:40",
        "match": "Detroit Tigers vs. Minnesota Twins",
        "slug": "mlb-det-min-2026-09-01",
        "gamePk": 823661,
    },
    {
        "time_hkt": "07:40",
        "match": "Miami Marlins vs. Kansas City Royals",
        "slug": "mlb-mia-kc-2026-09-01",
        "gamePk": 824070,
    },
    {
        "time_hkt": "07:40",
        "match": "Milwaukee Brewers vs. Chicago Cubs",
        "slug": "mlb-mil-chc-2026-09-01",
        "gamePk": 824633,
    },
    {
        "time_hkt": "08:05",
        "match": "Athletics vs. Texas Rangers",
        "slug": "mlb-oak-tex-2026-09-01",
        "gamePk": 822854,
    },
    {
        "time_hkt": "08:10",
        "match": "Chicago White Sox vs. Houston Astros",
        "slug": "mlb-cws-hou-2026-09-01",
        "gamePk": 824148,
    },
    {
        "time_hkt": "08:40",
        "match": "Baltimore Orioles vs. Colorado Rockies",
        "slug": "mlb-bal-col-2026-09-01",
        "gamePk": 824313,
    },
    {
        "time_hkt": "09:38",
        "match": "New York Yankees vs. Los Angeles Angels",
        "slug": "mlb-nyy-laa-2026-09-01",
        "gamePk": 823984,
    },
    {
        "time_hkt": "09:40",
        "match": "Philadelphia Phillies vs. Arizona Diamondbacks",
        "slug": "mlb-phi-ari-2026-09-01",
        "gamePk": 825038,
    },
    {
        "time_hkt": "10:10",
        "match": "St. Louis Cardinals vs. Los Angeles Dodgers",
        "slug": "mlb-stl-lad-2026-09-01",
        "gamePk": 823908,
    },
]
